# Generated by Django 5.0.2 on 2024-02-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uavs', '0001_initial'),
    ]

    operations = [
    ]
