# Generated by Django 5.0.2 on 2024-02-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uavs', '0002_remove_uav_renter_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
