### Auth tests
POST http://127.0.0.1:8000/api/register/
Content-Type: application/Json

{"username": "john_do", "password": "password123", "email": "johnd@example.com"}
### Done

###
POST http://127.0.0.1:8000/api/login/
Content-Type: application/Json

{"username": "john_do", "password": "password123"}
### Done

###
GET http://127.0.0.1:8000/api/test-token/
Authorization: token a74a03254eed0e55e158ac6660451f2d79109b79
### Done



# Create a UAV (replace the token value with the actual token)
POST http://localhost:8000/api/uavs/create/
Content-Type: application/json
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

{

    "brand": "SampleBrand",
    "model": "SampleModel",
    "weight": 50.5,
    "category": "SampleCategory"

}
### Done
GET http://localhost:8000/api/uavs/user/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

### Retrieve a UAV by ID (replace the token value with the actual token)  Done
GET http://localhost:8000/api/uavs/8/retrieve/
Authorization: Token f1cac8f547eb88d6503715dbff6e58c833ed65d3

### List available UAVs (replace the token value with the actual token) Done
GET http://localhost:8000/api/uavs/list/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

### Update a UAV by ID (replace the token value with the actual token) Done
PUT http://localhost:8000/api/uavs/2/update/
Content-Type: application/json
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

{
    "brand": "UpdatedBrand",
    "model": "UpdatedModel",
    "weight": 55.5,
    "category": "UpdatedCategory"
}

### Delete a UAV by ID (replace the token value with the actual token) Done
DELETE http://localhost:8000/api/uavs/2/delete/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79


### Create a rental (requires token authentication) Done 
POST http://localhost:8000/api/rentals/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79
Content-Type: application/json

{
    "id": 1,
    "start_date": "2024-03-01",
    "end_date": "2024-03-10"
}

### Retrieve, update, and delete a specific rental (requires token authentication) Done
GET http://localhost:8000/api/rentals/1/ 
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

###
PUT http://localhost:8000/api/rentals/1/  # Replace 1 with the ID of the rental Done
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79
Content-Type: application/json

{
    "uav": 2,  
    "start_date": "2024-03-05",
    "end_date": "2024-03-15"
}

### Done
DELETE http://localhost:8000/api/rentals/4/ 
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

### List rentals associated with the authenticated user (requires token authentication) Done
GET http://localhost:8000/api/rentals/user/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79

### List rentals associated with the owner of the uav(requires token authentication) currently Done
GET http://localhost:8000/api/rentals/owner/
Authorization: Token a74a03254eed0e55e158ac6660451f2d79109b79